[package]
name = "txnos-terminal"
version = "0.0.1"
edition = "2024"

[dependencies]
reqwest = { version = "^0.12", features = ["json"] }
tokio = { version = "^1.12", features = ["full"] }
serde = "^1.0"
serde_json = "^1.0"